name: commons_dependencies
description: A new Flutter package project.
version: 0.0.1
homepage: https://www.cvc.com.br/
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  flutter_modular: ^3.3.1    
  localization: ^1.0.0
  get: ^4.3.6
  # responsys:
  #   path: ../packages/responsys
  platform_widget:
    path: ../packages/platform_widget  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
