name: responsys
description: A new flutter plugin project.
version: 0.0.1
author:
homepage: https://www.cvc.com.br/
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.responsys
        pluginClass: ResponsysPlugin
      ios:
        pluginClass: ResponsysPlugin
